Ico 866
Consdata/consdata.github.io pull request #123
Opened 2021-04-25 15:00 UTC by jwilczewski

Aktualizacja informacji dot. darmowych dystrybucji jdk.

2021-04-26 07:21 UTC, szczurmys commented
W poprzednim wpisie (pewnie jako osobny PR), dodałbym informację o aktualizacji z linkiem do tego wpisu (oczywiście jak już będzie opublikowany). 

A sama aktualizacja jak dla mnie ok. Nie mam uwag :)

2021-04-26 11:40 UTC, pogoma commented on _posts/pl/2021-04-26-java-darmowa-czy-nie-update.md
> +- [Java darmowa, czy nie?](https://blog.consdata.tech/2019/03/27/java-darmowa-czy-nie.html)
Zamiast linku skorzystaj proszę z post_url. Przykład użycia masz w 2020-07-30-axon-kompleksowe-testowanie-aplikacji.md:
```
Powszechnie wiadomo, że kod dobrze pokryty testami jest dużo bardziej podatny na rozwój - wszak nie musimy obawiać się, że nasza zmiana spowoduje np. powrót znanego wcześniej błędu.
[W poprzednim wpisie]({% post_url pl/2020-06-08-microservices-on-axon %}) opisałem swoje zmagania z migracją monolitu do mikroserwisów na Axonie, umyślnie pomijając kwestię związaną z testami.
```

2021-04-26 11:42 UTC, pogoma commented on _posts/pl/2021-04-26-java-darmowa-czy-nie-update.md
> +_Microsoft dołącza do dystrybutorów java jdk. To dobry moment żeby sprawdzić jak rozwinęła się sytuacja z wydawaniem darmowych dystrybucji od czasu kiedy Oracle zmienił tryb licencjonowania. Pisaliśm
Zamiast linku skorzystaj proszę z post_url. Przykład użycia masz w 2020-07-30-axon-kompleksowe-testowanie-aplikacji.md:
```
Powszechnie wiadomo, że kod dobrze pokryty testami jest dużo bardziej podatny na rozwój - wszak nie musimy obawiać się, że nasza zmiana spowoduje np. powrót znanego wcześniej błędu.
[W poprzednim wpisie]({% post_url pl/2020-06-08-microservices-on-axon %}) opisałem swoje zmagania z migracją monolitu do mikroserwisów na Axonie, umyślnie pomijając kwestię związaną z testami.
```

2021-04-26 11:58 UTC, pogoma commented on _posts/pl/2021-04-26-java-darmowa-czy-nie-update.md
> +_Microsoft dołącza do dystrybutorów java jdk. To dobry moment żeby sprawdzić jak rozwinęła się sytuacja z wydawaniem darmowych dystrybucji od czasu kiedy Oracle zmienił tryb licencjonowania. Pisaliśm
Java i JDK moim zdaniem z wielkich liter. Zastanawiam się czy Java przed JDK ma sens (ale tu nie będę się upierać :) )

2021-04-26 12:06 UTC, adampij requested changes
To jeden z tych wpisów, w którym nie ma czego poprawiać. Postanowiłem przy okazji na bazie poprzedniego artykułu spojrzeć, po których frazach najczęściej userzy zdecydowali się wejść i przeczytać tamten artykuł.
![Zaznaczenie_569](https://user-images.githubusercontent.com/57706060/116079717-6edab980-a698-11eb-84e5-73ad47376c46.png)
Jeżeli którąś z nich można by naturalnie umieścić w tytule, któregoś z akapitów, to byłoby świetnie. Oczywiście chodzi o naturalne wtrącenie, a nie żeby stworzyć jakąś dziwną kombinację, która będzie gryźć po oczach.

2021-04-26 12:07 UTC, pogoma commented on _posts/pl/2021-04-26-java-darmowa-czy-nie-update.md
> +_Microsoft dołącza do dystrybutorów java jdk. To dobry moment żeby sprawdzić jak rozwinęła się sytuacja z wydawaniem darmowych dystrybucji od czasu kiedy Oracle zmienił tryb licencjonowania. Pisaliśm
Java i JDK moim zdaniem z wielkich liter. Zastanawiam się czy Java przed JDK ma sens (ale tu nie będę się upierać :) )

2021-04-29 18:59 UTC, pogoma approved these changes

2021-04-30 07:43 UTC, adampij approved these changes

2021-04-30 09:34 UTC, merged