czy wiesz że - lipiec
Consdata/consdata.github.io pull request #132
Opened 2021-07-06 08:53 UTC by martini449

2021-07-07 11:58 UTC, Chrrapek requested changes

2021-07-07 11:58 UTC, Chrrapek commented on _posts/pl/2021-07-06-metaprogramowanie-w-javie.md
> +W tym artykule dowiemy się jak przy tworzeniu własnej adnotacji, używać adnotacji `@Target`.
Zmieniłbym składnię tego zdania, moim zdaniem lepiej brzmi 
W tym artykule dowiemy się jak używać adnotacji `@Target` przy tworzeniu własnej adnotacji.

2021-07-07 11:58 UTC, Chrrapek commented on _posts/pl/2021-07-06-metaprogramowanie-w-javie.md
> +Adnotacje tworzy się w następujący sposób. Używa się deklaracji interface ze znakiem `@` na początku. Taka adnotacja nic nie robi, lecz program nie wyrzuci błędu przy kompilacji.
Połączyłbym te dwa pierwsze zdania
```suggestion
Adnotacje tworzy się używając deklaracji interface ze znakiem `@` na początku. Taka adnotacja nic nie robi, lecz program nie wyrzuci błędu przy kompilacji.
```

2021-07-08 09:31 UTC, Porkite approved these changes

2021-07-08 09:31 UTC, Porkite commented on _posts/pl/2021-07-08-metaprogramowanie-w-javie.md
> +Powyższa adnotacja nie ma zdefiniowanego miejsca w którym możemy jej użyć. Aby to zrobić, należy dodać adnotację @Target, wraz z parametrami.
miejsca, w którym możemy jej użyć

2021-07-08 10:09 UTC, krzysztof83 approved these changes

2021-07-08 10:16 UTC, drolewski commented on _posts/pl/2021-07-08-metaprogramowanie-w-javie.md
> +`@Target` określa, w których miejscach konstruowana przez nas adnotacja może zostać użyta. Gdy zadeklarujemy, w których miejscach kodu jest możliwe użycie adnotacji, błędne jej umiejscowienie nie poz
Powtórzenie: w których. 
Drugie wystąpienie można zamienić na w jakich

2021-07-08 10:24 UTC, merged

2021-07-08 12:13 UTC, adampij reviewed
Dla celów SEO (opis będzie pojawiał się w przeglądarce, warto go mieć bo działa wyłącnzie na korzyść).

2021-07-08 12:13 UTC, adampij commented on _posts/pl/2021-07-08-metaprogramowanie-w-javie.md
> +---
description: @Target określa, w których miejscach konstruowana przez nas adnotacja może zostać użyta. Gdy zadeklarujemy, w których miejscach kodu jest możliwe użycie adnotacji, błędne jej umiejscowienie nie pozwoli na skompilowanie kodu.

2021-07-08 13:08 UTC, martini449 commented on _posts/pl/2021-07-08-metaprogramowanie-w-javie.md
> +---
https://github.com/Consdata/consdata.github.io/pull/133