Ico 908 cloud functions gen2
Consdata/consdata.github.io pull request #203
Opened 2022-08-12 15:35 UTC by Michuu93

2022-08-12 15:36 UTC, Michuu93 commented
Jeszcze muszę przejrzeć od góry do dołu i popoprawiać to co mi się nie podoba.

2022-08-17 07:09 UTC, ynleborg approved these changes

2022-08-17 07:09 UTC, ynleborg commented on _posts/pl/2022-08-31-cloud-functions-2.md
> +### Przetwarzanie współbierzne
współbieżne

2022-08-17 15:09 UTC, pogoma commented on _posts/pl/2022-08-31-cloud-functions-2.md
> +Możemy zdefiniować liczbę instancji, które mają być cały gotowe do obsługi żądań. Pozwala to skrócić czas obsługi żądania w przypadku tworzenia nowej instancji (cold start). Warto pamiętać również o
"cały gotowe" -> "cały czas gotowe"

2022-08-17 15:18 UTC, pogoma commented
Obrazek clouds.jpg nie spełnia wymagań - ma wymiary 1280x853 i jest w formacie jpg, a powinien być w formacie webp i mieć wymiary 1080x720px

2022-08-17 15:19 UTC, pogoma commented on _posts/pl/2022-08-31-cloud-functions-2.md
> +[Więcej informacji tutaj](https://cloud.google.com/functions/docs/configuring/concurrency)
Te linki się zlewają:
![image](https://user-images.githubusercontent.com/1863167/185177672-c18e7acb-6946-4f55-bd54-6b80ffd2195f.png)
Proponuję aby słowo oraz nie było częścią linka albo umieścić linki wyłącznie na słowie "tutaj"

2022-08-17 15:23 UTC, krzysztof83 commented on _posts/pl/2022-08-31-cloud-functions-2.md
> +Nowa generacja wprowadza natywne wsparcie dla platformy [Eventarc](https://cloud.google.com/eventarc/docs/overview), co rozszerza listę dostępnych wyzwalaczy funkcji o ponad [125 nowych](https://clou
Dla porównania,
tu chyba przecinek zbędny

2022-08-17 15:23 UTC, krzysztof83 commented on _posts/pl/2022-08-31-cloud-functions-2.md
> +Funkcje drugiej generacji są dostępne we wszystkich regionach w których dostępna jest pierwsza generacja oraz w dwóch nowych: europe-north1 (Finlandia), europe-west4 (Holandia).
Czy w europe-north1 (Finlandia), europe-west4 (Holandia) pierwsza wersja nie była dostępna? Czy wcale nie było tych regionów?

2022-08-18 12:12 UTC, Chrrapek commented
> Obrazek clouds.jpg nie spełnia wymagań - ma wymiary 1280x853 i jest w formacie jpg, a powinien być w formacie webp i mieć wymiary 1080x720px

Obrazki postów faktycznie mają być 1080x720px, ale nie mogą być webp. Niestety niektóre narzędzia do udostępniania postów (np. Linkedin) nie potrafią (a przynajmniej nie potrafiły jak to weryfikowałem z pół roku temu) czytać .webp i biorą pierwszy obrazek o innym rozszerzeniu, jaki znajdą (często było to zdjęcie autora).

Słowem - rozmiar zły, rozszerzenie ok

2022-08-18 12:21 UTC, Michuu93 commented
> > Obrazek clouds.jpg nie spełnia wymagań - ma wymiary 1280x853 i jest w formacie jpg, a powinien być w formacie webp i mieć wymiary 1080x720px
> 
> Obrazki postów faktycznie mają być 1080x720px, ale nie mogą być webp. Niestety niektóre narzędzia do udostępniania postów (np. Linkedin) nie potrafią (a przynajmniej nie potrafiły jak to weryfikowałem z pół roku temu) czytać .webp i biorą pierwszy obrazek o innym rozszerzeniu, jaki znajdą (często było to zdjęcie autora).
> 
> Słowem - rozmiar zły, rozszerzenie ok

poprawione

2022-08-18 12:49 UTC, Chrrapek requested changes

2022-08-18 12:49 UTC, Chrrapek commented on _posts/pl/2022-08-31-cloud-functions-2.md
> +W lutym tego roku Google wprowadziło w wersji poglądowej (public preview) nową generację usługi Cloud Functions (2nd gen). Architektura Google Cloud Function (2nd gen) została oparta o Cloud Run oraz
Nie jestem pewien, czy można coś "nieść względem". Może raczej "co wprowadza kilka ciekawych funkcjonalności względem [...]"?

2022-08-18 12:49 UTC, Chrrapek commented on _posts/pl/2022-08-31-cloud-functions-2.md
> +Możemy zdefiniować liczbę instancji, które mają być cały czas gotowe do obsługi żądań. Pozwala to skrócić czas obsługi żądania w przypadku tworzenia nowej instancji (cold start). Warto pamiętać równi
```suggestion
Możemy zdefiniować liczbę instancji, które mają być cały czas gotowe do obsługi żądań. Pozwala to skrócić czas obsługi żądania w przypadku tworzenia nowej instancji (cold start). Warto pamiętać również o tym, że płacimy za cały czas działania funkcji, również za potencjalny zimny start.
```

2022-08-18 13:20 UTC, Chrrapek approved these changes

2022-08-19 07:13 UTC, merged