Wprowadzenie do pisania pluginów w intellij
Consdata/consdata.github.io pull request #78
Opened 2020-08-12 08:02 UTC by m87

Na praktycznym przykładzie wprowadzę do pisania pluginów do intellij. Trochę doświadczeń ostatnio zebrałem i myślę, że warto się tym podzielić, bo doc intellij nie jest zbyt obszerny.

2020-08-12 08:08 UTC, glipecki commented
:+1:

2021-01-07 09:30 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Intellij IDEA to obecnie jedno z popularniejszych jeśli nie najpopularniejsze IDE dla Javy. Jedną z jego zalet jest duża baza pluginów, dostarczana przez samo JetBrains jak i społeczność. W tym artyk
- IntelliJ (duże J)
- odstęp przed nawiasem

2021-01-07 09:31 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +image:
brakuje obrazka

2021-01-07 09:31 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +
ta pusta linia słabo wygląda

2021-01-07 09:31 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +W platformie mamy do dyspozycji trzy podstawowe metody rozszerzenia IDE:
Przecinki na końcu pierwszego i drugiego punktu, kropka na końcu ostatniego

2021-01-07 09:33 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +- akcje - kod uruchamiany w momencie gdy użytkownik wprost kliknie np. w element menu kontekstowego lub paska narzędziowego
"listenery" i "extension pointy" nie są przetłumaczone, IMO lepiej nie tłumaczyć też "akcji"

2021-01-07 09:33 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +
ta pusta linia na początku i końcu wygląda słabo

2021-01-07 09:34 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Na githubie znajduje się [repo z pluginem](https://github.com/m87/article-app) oraz [repo z testową aplikacją](https://github.com/m87/article-test-app)
"repozytorium" zamiast "repo"?

2021-01-07 09:34 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Dokładnie co jak działa możecie przeczytać w dokumentacji IDE. Ja przedstawię je w praktyce. Stworzymy prosty plugin, który wykorzysta wszystkie opisane wyżej metody. Przykładowy plugin, na podstawie
Odstęp przed nawiasem

2021-01-07 09:35 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Przygodę z własnym pluginem rozpoczynamy od stworzenia nowego projektu typu `Intellij Platform Plugin`. Wygenerowana zostanie domyślna struktura katalogów oraz plik XML z manifestem(META-INF/plugin.x
Odstęp przed nawiasem

2021-01-07 09:36 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Mając już gotowy projekt bazowy możemy przejść do implementacjia akcji. Dodamy element do menu kontekstowego edytora oraz drzewa projektu - przycisk 'Generuj'. Narazie będzie wyświetlał tylko prostu
"prostu" do usunięcia

2021-01-07 09:36 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Narazie implementacja actionPerformed sprowadzać będzie się do wyświetlenia okan dialogoweg. Do tego celu wykorzystamy gotowego helpera w platformie - Messages:
"dialogoweg" -> "dialogowego"

2021-01-07 09:38 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Atrybut `id` to unikalny identyfikator naszej akcji(zwykle `Fully qualified name` klasy), w atrybucie `class` wskazujemy implementację akcji. W atrybucie `text` określamy tekst przycisku w menu. Wewn
Odstęp przed nawiasem

2021-01-07 09:42 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +W powyższym kodzie skorzystaliśmy z jednego z podstawowych elementów platformy tj. `PSI`(`Program Structure Interface`). Najprościej rzeczy ujmując, PSI odpowiada w platformie za parsowanie plików i
odstępy przed nawiasami

2021-01-07 09:45 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +            return String.join("\n", doc.entrySet().stream().map(e -> e.getKey() + ": " + e.getValue()).collect(Collectors.toList()));
Collectors.joining

2021-01-07 09:48 UTC, Chrrapek requested changes

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Intellij IDEA to obecnie jedno z popularniejszych jeśli nie najpopularniejsze IDE dla Javy. Jedną z jego zalet jest duża baza pluginów, dostarczana przez samo JetBrains jak i społeczność. W tym artyk
Większoś -> większość, brakuje spacji przed otwarciem nawiasu, JetBrains zamiast JestBrains. Sprawdziłem i brakuje jeszcze przecinka przed "jak i" w drugim zdaniu.

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +- akcje - kod uruchamiany w momencie gdy użytkownik wprost kliknie np. w element menu kontekstowego lub paska narzędziowego
Wydaje mi się, że "wprost" można pominąć - wiadomo o co chodzi, ale w moim odczuciu jest niepotrzebne

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +- listenery - pozwalają nasłuchiwać na eventy generowane przez platforme lub inne pluginy
platform**ę**

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +- `*.platform` - zawiera interfejsy i klasy potrzebne do implementacji serwisów, akcji, ui, rozszerzeń itd.
Może troszkę się czepiam, ale UI to jednak skrót, więc napiszmy go wielkimi literami :)

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Mając już gotowy projekt bazowy możemy przejść do implementacjia akcji. Dodamy element do menu kontekstowego edytora oraz drzewa projektu - przycisk 'Generuj'. Narazie będzie wyświetlał tylko prostu
"implementacjia" mamma mia :smile: 
"Na razie" - brakuje spacji

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Każda akcja w platformie musi rozszerzać abstrakcyjną klasę AnAction i implementować metodę actionPerformed. Tworzym zatem naszą akcję, którą nazwiemy DocAction.
Tworzym -> tworzymy

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Narazie implementacja actionPerformed sprowadzać będzie się do wyświetlenia okan dialogoweg. Do tego celu wykorzystamy gotowego helpera w platformie - Messages:
Raz jeszcze "na razie" - ze spacją.
"dialogoweg" -> "dialogowego"

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Atrybut `id` to unikalny identyfikator naszej akcji(zwykle `Fully qualified name` klasy), w atrybucie `class` wskazujemy implementację akcji. W atrybucie `text` określamy tekst przycisku w menu. Wewn
Brakuje spacji przed otwarciem nawiasu

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Po uruchomieniu projektu i klknięciu prawym przyciskiem myszny an edytor pliku w menu kontekstowym pokaże nam się opcja 'Generuj'
an edytor -> na edytor

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Po uruchomieniu w miejscu przycisku 'Generuj' pojawi się przycisk 'Dokumentacja', kierujący do naszego submenu.
Chyba lepiej będzie napisać "podmenu", "submenu" brzmi już za bardzo "Ponglish" jak dla mnie

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Plugin będzie generował dokumentację na podstawie adnotacji `Doc`. Dlatego też nie ma sensu uruchamiać akcji na plikach, które takiej adnotacji nie zawierają. W naszym pluginie przycisk 'Dokumentacja
```suggestion
Plugin będzie generował dokumentację na podstawie adnotacji `Doc`, dlatego też nie ma sensu uruchamiać akcji na plikach, które takiej adnotacji nie zawierają. W naszym pluginie przycisk 'Dokumentacja' pozostawimy widocznym, ale będzie nieaktywny jeśli celem naszej alcji jest plik nie zawierający adnotacji `Doc`. Widoczność i aktywność przycisku aktualizujemy w metodzie `update` wywoływanej w przypadku, gdy użytkownik kliknie w jakiś element interfejsu zawierający tę akcję lub grupę:
```

(sklejenie dwóch zdań w jedno i literówka)

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +W powyższym kodzie skorzystaliśmy z jednego z podstawowych elementów platformy tj. `PSI`(`Program Structure Interface`). Najprościej rzeczy ujmując, PSI odpowiada w platformie za parsowanie plików i
"Najprościej rzeczy ujmując" -> "Najprościej rzecz ujmując"
Brakuje spacji przed otwarciami nawiasów

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Dokumentacja będzie składać się z wierszy zwierających nazwę dokumentowanego elementu(np. nazwa pola) oraz opisu z adnotacji. Przyjmując, że na wejsciu mamy model PSI pliku z kodem, wygenerowanie tak
Jeszcze raz spacja przed otwarciem nawiasu

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Korzystając z PSI przechodzimy po wszystkich klasach w pliku oraz ich polach i metodach. Jeśli zawierają adnotacją `Doc`, to do wierszy dokumentacji dodajemy nazwę pola, znak ':' oraz wartość adnotac
"Jeśli zawierają adnotacją" -> "Jeśli zawierają adnotację" 
"Nie możemy jednak wartości adnotacji pobrać wprost. Nie jest to String." - sklejmy to w jedno zdanie, na przykład "Nie możemy [...], gdyż nie jest to String". 
Ponownie spacja przed otwarciem nawiasu

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Przy zapisie do pliku zachaczamy o kolejny ważny element platformy - warstwę plików wirtualnych(Virtual File System). Udostępnia ona wspólne api do wszystkich operacji na plikach niezależnie od ich p
"zachaczamy" -> "zahaczamy"
Spacja przed otwarciem nawiasu

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Listenery pozwalaja pluginowi reagować na eventy w ramach platformy, emitowane czy to przez IDE, czy przez inne pluginy. W przykładzie, plugin najpierw wyemituje event po zapisie dokumentacji. Jeśli
"W przykładzie plugin" - niepotrzebny przecinek
"zaprezentuja" - "zaprezentuje"

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +W efekcie po zapisie dokumentacji do pliku, automatycznie otworzy nam się edytor pliku dokumentacji.
Niepotrzebny przecinek

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +W ramach naszego projektu stworzym rozszerzenie dla extension pointa `com.intellij.documentationProvider`. Pozwala on na wzbogacenie o własne treści, dokumetancji prezentowanej np. w `Quick Documenta
```suggestion
W ramach naszego projektu stworzymy rozszerzenie dla extension pointa `com.intellij.documentationProvider`. Pozwala on na wzbogacenie  dokumetancji prezentowanej np. w `Quick Documentation`(Ctrl + Q)` o własne treści.
```

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Tak zdefiniowany provider możemy teraz zdefiniować w manifeście plaginu jak rozszerzenie dla `documentationProvider`:
"plaginu" -> "pluginu"

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Po uruchomieniu pluginu, przechodzimy do klasy `UseCase`. Najeżdżamy na typ `TestClass` i wcisakamy Ctrl + Q. Po jednokrotnym wciśnięciu skrót pojawi się popu z wygnerowaną dokumentacją:
"popu" -> "popup"

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Oczywiście w przypadku innych externsion pintów, potrzeba będzie zdefiniować inne mechanizmy. Co do zasady sprawa jest jednakowa dla wszystkich etension pointów. Definujemy implementacje dla konkretn
```suggestion
Oczywiście w przypadku innych extension pointów potrzeba będzie zdefiniować inne mechanizmy. Co do zasady sprawa jest jednakowa dla wszystkich extension pointów. Definujemy implementacje dla konkretnego przypadku i łaczymy ją z określonym extensionPointem w manifeście.
```

Dużo powtórzeń, ale chyba nie damy rady ich tu uniknąć

2021-01-07 09:48 UTC, Chrrapek commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Gotowy plugin pakujemy do paczki klikając prawym przyciskiem myszy na projekt pluginu i wybieramy `Prepare plugin module ... for deployment`. Wygenerowany JAR pluginu możemy opublikować w repo Intell
"prywatnego repo" (w linku)

2021-01-07 09:48 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Korzystając z PSI przechodzimy po wszystkich klasach w pliku oraz ich polach i metodach. Jeśli zawierają adnotacją `Doc`, to do wierszy dokumentacji dodajemy nazwę pola, znak ':' oraz wartość adnotac
Odstęp przed nawiasem

2021-01-07 09:49 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Helper ten automatycznie rozwiąże nam wszystkie wyrażenie z adnotacji. Należy jednago pamiętać o tym aby projekt był zaindeksowany, a elementy wyrażenia widoczne w ramach projektu.
jednago -> jednak

2021-01-07 09:50 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Przy zapisie do pliku zachaczamy o kolejny ważny element platformy - warstwę plików wirtualnych(Virtual File System). Udostępnia ona wspólne api do wszystkich operacji na plikach niezależnie od ich p
Odstęp przed nawiasem

2021-01-07 09:51 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Podobnie jak w innych systemach, Intellij udostępnia gotowe definicje okien dialogowych dla np. zapisu plików. W naszym przypadku jest to `FileSaverDialog`. Po wybraniu pliku i kliknięciu 'zapisz', d
IntelliJ (duże J)

2021-01-07 09:53 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +```java
xml

2021-01-07 09:53 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +   event.getProject().getMessageBus().syncPublisher(Topic.create("com.consdata.article.DocSaved", DocSaved.class)).onSave(vFile);
Połam linię - słabo się to prezentuje

2021-01-07 09:54 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Atrybut `class` zawiera implementację interfejsu naszego listenera, zdefiniowanego w polu `topic`. Listenery działające w obrębie całej aplikacji definiujemy w węźle `applicationListeres`.
applicationListeres?

2021-01-07 09:54 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Ostatnim elementem jaki poznamy będa `Extension Pointy`. Są to wprost nazwane interfejsy, które pozwalają na rozszerzenie konkretnych elementów platformy lub innych pluginów. Pełna lista dostępnych e
będą (ą)

2021-01-07 09:55 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +
1. Może wrzućmy pełną klasę?
2. Usuńmy puste linie z początku i końca

2021-01-07 09:56 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +        return String.join("<br/>", doc.entrySet().stream().map(e -> "<b>" + e.getKey() + "</b>: " + e.getValue()).collect(Collectors.toList()));
Collectors.joining

2021-01-07 09:57 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Po uruchomieniu pluginu, przechodzimy do klasy `UseCase`. Najeżdżamy na typ `TestClass` i wcisakamy Ctrl + Q. Po jednokrotnym wciśnięciu skrót pojawi się popu z wygnerowaną dokumentacją:
popu -> popup

2021-01-07 09:58 UTC, pogoma commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Gotowy plugin pakujemy do paczki klikając prawym przyciskiem myszy na projekt pluginu i wybieramy `Prepare plugin module ... for deployment`. Wygenerowany JAR pluginu możemy opublikować w repo Intell
rywatnego repo -> prywatnego repo

2021-01-07 14:01 UTC, adampij approved these changes

2021-01-07 14:01 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Dokładnie co jak działa możecie przeczytać w dokumentacji IDE. Ja przedstawię je w praktyce. Stworzymy prosty plugin, który wykorzysta wszystkie opisane wyżej metody. Przykładowy plugin, na podstawie
dla dobra SEO żeby jak najczęściej wmieścić frazę "plugin intelliJ"
Ja natomiast przedstawię ujęcie praktyczne, w ramach którego stworzymy prosty plugin ==> Ja natomiast przedstawię ujęcie praktyczne, w ramach którego stworzymy prosty **plugin dla IntelliJ**

2021-01-07 23:19 UTC, m87 commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +- extension pointy - interfejsy pozwalające na rozszerzenie konkretnych elementów platformy lub innych pluginów
dałem przecinki i kropkę

2021-01-08 09:19 UTC, martini449 commented
@pogoma @Chrrapek Przejrzycie kontrolnie poprawki?

2021-01-08 13:54 UTC, Chrrapek approved these changes

2021-01-11 07:24 UTC, adampij requested changes

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Więcej informacji o tym, co i jak działa, możecie znaleźć w dokumentacji IDE. Ja natomiast przedstawię ujęcie praktyczne, w ramach którego stworzymy prosty plugin dla IntelliJ, który wykorzysta wszys
jeszcze jedna spacja przed nawiasem nam tutaj się zapodziała:

dla klas Javy (do tego

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Przygodę z własnym pluginem rozpoczynamy od stworzenia nowego projektu typu `Intellij Platform Plugin`. Wygenerowana zostanie domyślna struktura katalogów oraz plik XML z manifestem (META-INF/plugin.
literówka:
uniklany ==> unikalny

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Mając już gotowy projekt bazowy możemy przejść do implementacja akcji. Dodamy element do menu kontekstowego edytora oraz drzewa projektu - przycisk 'Generuj'. Na razie będzie wyświetlał tylko popup z
literówka:
implementacja ==> implementacji.

Zmutowałbym też dwa zdania w jedno:
Mając już gotowy projekt bazowy możemy przejść do implementacji akcji czyli dodamy element do menu kontekstowego edytora, a do drzewa projektu - przycisk 'Generuj'.

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Atrybut `id` to unikalny identyfikator naszej akcji (zwykle `Fully qualified name` klasy), w atrybucie `class` wskazujemy implementację akcji. W atrybucie `text` określamy tekst przycisku w menu. Wew
literówka
Wewnatrz węzła --> Wewnątrz węzła

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Po uruchomieniu projektu i klknięciu prawym przyciskiem myszny na edytor pliku w menu kontekstowym pokaże nam się opcja 'Generuj'
literówka
myszny ==> myszy

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +W powyższym kodzie skorzystaliśmy z jednego z podstawowych elementów platformy tj. `PSI` (`Program Structure Interface`). Najprościej rzecz ujmując, PSI odpowiada w platformie za parsowanie plików i
literówka
zwartych ==> zawartych

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Dokumentacja będzie składać się z wierszy zawierających nazwę dokumentowanego elementu (np. nazwa pola) oraz opisu z adnotacji. Przyjmując, że na wejsciu mamy model PSI pliku z kodem, wygenerowanie t
literówka:
na wejsciu mamy model ==> na wejściu mamy model

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Listenery pozwalaja pluginowi reagować na eventy w ramach platformy, emitowane czy to przez IDE, czy przez inne pluginy. W przykładzie plugin najpierw wyemituje event po zapisie dokumentacji. Jeśli p
literówka
zposób ==> sposób

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +W `fetchExternalDocumentation` generujemy dokumentację dla wskazanej klasy analogicznie jak w akcji, tylko dla jednej klasy. Dodatkowo wzbogacamy dokumentację o znacznik HTML(w oknie `QuickDocumentat
spacyjka przed nawiasem
o znacznik HTML (w

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Tak zdefiniowany provider możemy teraz zdefiniować w manifeście pluginu jak rozszerzenie dla `documentationProvider`:
literówka
 pluginu jak rozszerzenie ==>  pluginu jako rozszerzenie

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Po uruchomieniu pluginu, przechodzimy do klasy `UseCase`. Najeżdżamy na typ `TestClass` i wybieramy Ctrl + Q. Po wywołaniu skrótu pojawi się popup z wygnerowaną dokumentacją:
literówka
wygnerowaną ==> wygenerowaną

2021-01-11 07:24 UTC, adampij commented on _posts/2021-01-11-pisanie-pluginow-do-intellij.md
> +Po ponownym użyciu skrótu odtworzy się szuflada:
tutaj się upewnię, bo nie wiem jaki miałeś zamysł:
szuflada ma się faktycznie "odtworzyć" czy miałeś na myśli "otworzyć". Pytam, bo gdy rozumuję to, tak jak ja się domyślam, to do szuflady pasuje mi bardziej otwieranie.

2021-01-11 10:48 UTC, adampij approved these changes
Znakomicie :)

2021-01-11 12:27 UTC, martini449 approved these changes

2021-01-11 12:28 UTC, merged